debug: true
server:
  port: 3010
auth0:
  audience: https://quickstarts/api
  url: https://corporate.auth0.com/oauth/token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://corporate.auth0.com/